package com.example.spacemarine.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "space_marines")
public class SpaceMarine {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // >0, unique, generated by DB

    @NotNull(message = "name must not be null")
    @NotBlank(message = "name must not be blank")
    private String name;

    @NotNull(message = "coordinates must not be null")
    @Embedded
    @Valid
    private Coordinates coordinates;

    @NotNull
    @Column(name = "creation_date", nullable = false, updatable = false)
    private LocalDateTime creationDate = LocalDateTime.now();


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "chapter_id", nullable = false)
    @NotNull(message = "chapter must not be null")
    @JsonBackReference
    private Chapter chapter;

    @NotNull(message = "health must not be null")
    @Min(value = 1, message = "health must be > 0")
    private Long health;

    @NotNull(message = "achievements must not be null")
    @Column(length = 1000)
    private String achievements;

    private double height;

    @Enumerated(EnumType.STRING)
    private Weapon weaponType; // may be null

    public SpaceMarine() {}




    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public Coordinates getCoordinates() {
        return coordinates;
    }

    public LocalDateTime getCreationDate() {
        return creationDate;
    }

    public Chapter getChapter() {
        return chapter;
    }

    public Long getHealth() {
        return health;
    }

    public String getAchievements() {
        return achievements;
    }

    public double getHeight() {
        return height;
    }

    public Weapon getWeaponType() {
        return weaponType;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = coordinates;
    }

    public void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }

    public void setChapter(Chapter chapter) {
        this.chapter = chapter;
    }

    public void setHealth(Long health) {
        this.health = health;
    }

    public void setAchievements(String achievements) {
        this.achievements = achievements;
    }

    public void setHeight(double height) {
        this.height = height;
    }

    public void setWeaponType(Weapon weaponType) {
        this.weaponType = weaponType;
    }
}
